---
- name: A simple file playbook
  hosts: web
  gather_facts: yes
  connection: ssh
  become: yes

  tasks:
   - name: make a directory
     file:
       path: /etc/ansible/facts.d/
       state: directory
       mode: 777
       recurse: yes

   - name: use shell module with wildcarding
     shell: echo $HOME >> ~/output/path.txt

