---
- name: Template with a loop
  hosts: fry
  connection: ssh
  gather_facts: no

  # these variables are used in the template ship.cfg.j2
  vars:
    crew:
      Zapp Brannigan:
        description: ship captain, lots of medals
        skills: leader, tactics, karaoke
      Kif:
        description: lieutenant
        skills: devoted, quiet
      Amy:
        description: PhD
        skills: engineering, physics, communication


  tasks:
    - name: Running a looping jinja template
      template:  
        src: templates/mission-orders.txt.j2    # name of the template on ansible controller
        dest: "~/{{ item.mission }}-mission-orders.txt"  # name of the completed file to be placed on the target system
      vars:
          planet: "{{ item.planet }}"
      loop:   # each time through the loop, each dict (list entry) will be an "item"
          - {"mission": "primary", "planet": "luna park"}
          - {"mission": "secondary", "planet": "cineplex 14"}  ## This is the list we want to loop across
